name: Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint # Ensure lint job completes successfully
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test # Ensure test job completes successfully
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        # Replace with your actual deployment commands
        run: |
          echo "Deploying..."
          # Example: Deploying to a server using SSH
          # ssh user@your-server "cd /path/to/your/app && git pull && npm install && npm run start"
          # Example: Deploying to a cloud provider (e.g., AWS, Azure, GCP)
          # ... (your cloud provider deployment commands)